services:
  pingora:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - "./config.yaml:/app/config.yaml"

  backend:
    image: "backend:dotnet"
    network_mode: "host"