services:
  traefik:
    image: "registry.docker.com/library/traefik:v2.10"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8081"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: "host"

  backend:
    image: "backend:dotnet"
    labels:
      - "traefik.enable=true"
      - "traefik.port=5000"
      - "traefik.http.routers.backend.rule=Host(`traefik.example`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
    network_mode: "host"